import Head from "next/head";
import Link from "next/link";

import TeamRocket from "@/images/TeamRocket";

import styles from "./styles/Layout.module.css";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Hockinson Math</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>

      <header className={styles.head}>
        <Link href="/" className={styles.headLeft}>
          <div className={styles.logo}>
            <TeamRocket />
          </div>
        </Link>

        <nav className={styles.headRight}>
          <Link href="/blog">Blog</Link>
          <Link href="/about">About</Link>
        </nav>
      </header>

      <main className={styles.main}>{children}</main>
    </>
  );
}
